"use client"

import { RootState } from "@/redux/store";
import {
    Modal,
    ModalContent,
    ModalHeader,
    ModalBody,
    ModalFooter,
    Button,
    Checkbox,
  } from "@heroui/react";
import { useSelector, useDispatch } from "react-redux";
import Image from "next/image";
import { useState } from "react";
import { useRouter } from "next/navigation";
  
  export default function DisclamerModal({open, closeFunction}: {open: boolean, closeFunction: React.Dispatch<React.SetStateAction<boolean>>}) {
    const dispatch = useDispatch();
    const [accepted, setAccepted] = useState(false);
    const [accepted1, setAccepted1] = useState(false);
    const router = useRouter();

    return (
      <>
        {/* <Button onPress={onOpen}>Open Modal</Button> */}
        <Modal
          onClose={() => {closeFunction(false); router.push("/symptom-bot-dtls");}}
          isOpen={open}
          size="5xl"
        //   style={{ backgroundColor: 'var(--color-primary-lite)' }}
        >
          <ModalContent>
            {(onClose) => (
              <>
                <ModalHeader className="flex flex-col gap-1 font-extrabold">Terms & Conditions</ModalHeader>
                <ModalBody className="px-10 max-h-[72vh] overflow-y-auto">
                    <h3 className=" font-bold text-slate-600">1. Disclaimer – Interactive Symptoms Bot at Nextcare.Life </h3>
                    <p className=" font-light pl-4">
                        The Interactive Symptoms Bot at Nextcare.Life is designed to provide preliminary symptom assessment and general health guidance based on the information entered by users. It does not provide a definitive diagnosis, medical advice, or treatment recommendations. The bot is not a substitute for professional medical consultation, diagnosis, or treatment.
                    </p>
                    <h3 className=" font-bold text-slate-600">2. Not a Medical Diagnosis Tool </h3>
                    <p className=" font-light pl-4">
                        The bot analyzes symptoms using a database of medical conditions and best practices, but it cannot replace a doctor’s expertise. The results generated by the bot are informational only and should not be considered medical advice.
                    </p>
                    <h3 className=" font-bold text-slate-600">3. Not for Emergency Use  </h3>
                    <p className=" font-light pl-4">
                        If you experience severe or life-threatening symptoms such as chest pain, breathing difficulty, loss of consciousness, seizures, or severe bleeding, seek immediate medical attention by visiting the nearest hospital or calling emergency services. The Symptoms Bot is not designed for emergency decision-making and should never be used in urgent medical situations.
                    </p>

                    <h3 className=" font-bold text-slate-600">4.  Consultation with a Medical Professional is Advised  </h3>
                    <p className=" font-light pl-4">
                        While the bot may suggest possible causes for your symptoms, you should always follow up with a qualified doctor for a professional evaluation. If you are unsure about your symptoms, we recommend proceeding to our 5-Minute Clinical Consult (Telemedicine) Service to speak with a licensed doctor.
                    </p>

                    <h3 className=" font-bold text-slate-600">5.  Accuracy and Limitations  </h3>
                    <p className=" font-light pl-4">
                        The bot’s responses are based on a structured question-answer system and medical databases. However, the following factors may affect accuracy:
                    </p>
                    <ul className="list-disc pl-8 mt-2 space-y-1 font-light">
                      <li>Incomplete or incorrect symptom entries may lead to misleading results.</li>
                      <li>Individual medical history, allergies, and risk factors are not always fully accounted for.</li>
                      <li>Certain rare or complex conditions may not be identified accurately.</li>
                    </ul>

                    <h3 className=" font-bold text-slate-600">6. No Prescriptions or Medication Recommendations  </h3>
                    <p className=" font-light pl-4">
                        The Symptoms Bot does not prescribe medications, dosages, or treatments. If medical treatment is required, please consult a licensed healthcare provider.
                    </p>
                    <h3 className=" font-bold text-slate-600">7.   Privacy and Data Security   </h3>
                    <p className=" font-light pl-4">
                        At Nextcare.Life, we prioritize your privacy and security. When using the Symptoms Bot:
                    </p>
                    <ul className="list-disc pl-8 mt-2 space-y-1 font-light">
                      <li>Your data is securely encrypted and protected.</li>
                      <li>We do not sell or share your personal health information with third parties.</li>
                      <li>Users may choose to delete their health assessments at any time.</li>
                    </ul>
                    <p className=" font-light pl-4">
                        For detailed information on how we protect your data, please refer to our Privacy Policy.
                    </p>
                    <div className="mt-10">
                      <Checkbox isSelected={accepted} onValueChange={setAccepted} className="font-extrabold" color="success">
                        I have read and agree to the terms and conditions.
                      </Checkbox>
                      <Checkbox isSelected={accepted1} onValueChange={setAccepted1} className="font-extrabold" color="success">
                        I accept the terms and conditions (Required before proceeding)
                      </Checkbox>
                    </div>
                </ModalBody>
                <ModalFooter>
                  <Button color="primary" variant="faded" onPress={() => router.push("/symptom-bot-dtls")}>
                    Cancel
                  </Button>
                  <Button color="primary" variant="solid" onPress={() => closeFunction(false)} isDisabled={!(accepted && accepted1)}>
                    Proceed
                  </Button>
                </ModalFooter>
              </>
            )}
          </ModalContent>
        </Modal>
      </>
    );
  }
  